<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sit_socialfeed"
 *
 * Auto generated by Extension Builder 2018-10-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Social Feed',
    'description' => 'A TYPO3 plugin which displays feeds from social media platforms',
    'category' => 'plugin',
    'author' => 'Patric Eckhart',
    'author_email' => 'patric.eckhart@steinbauer-it.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
